name: C/C++ CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cd folder
      run: cd ./Builds/LinuxMakefile
    - name: install deps
      run: apt-get install build-essential
    - name: make
      run: make CONFIG=Release Makefile
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
